version: '3.7'
services:
  config-server:
    build: ./config-server
    image: joelarauzo/spring-cloud-gateway-config-server
    ports:
      - "8888:8888"
  eureka-server:
    build: ./eureka-server
    image: joelarauzo/spring-cloud-gateway-eureka-server
    ports:
      - "8099:8099"
    depends_on:
     - config-server
  micro-crud:
    build: ./micro-crud
    image: joelarauzo/spring-cloud-gateway-micro-crud
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8099/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  api-gateway:
    build: ./api-gateway
    ports:
      - "8085:8085"
    depends_on: 
      - config-server
      - eureka-server
      - micro-crud 
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9000/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      